version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      # - mongodb_data_container:/data/db
      - ./database:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:


#   version: '3.8'

# # volumes:
#   # mongo_db: {}

# networks:
#   nesjs-network:
#     driver: bridge

# services:
#   mongodb:
#     container_name: mongodb
#     image: mongo:latest
#     restart: always
#     ports:
#       - 27017:27017
#     volumes:
#       # - mongo_db:/data/db
#       - ~/database:/data/db
#     networks:
#       - nesjs-network

#   nestjs:
#     container_name: nestjs_DEV
#     init: true
#     ports:
#       - 3000:3000
#     build: . 
#     command: npm run start:dev
#     volumes:
#       - .:/usr/src/app
#     environment:
#       PORT: 3000
#       MONGODB_URI: mongodb://mongodb:27017
#       DB_NAME: scores
#       NAME: estrella
#     depends_on:
#       - mongodb
#     networks:
#       - nesjs-network
